const Promise     = require('bluebird');
const capitalize  = require('lodash/capitalize');
const Liana       = require('forest-express-sequelize');
const Utils       = require('../../utils');

const _ = { capitalize };

module.exports = function(app, models, Renting) {
  const LEA = Liana.ensureAuthenticated;

  // NORMALLY THIS IS USELESS BECAUSE RENT ORDERS ARE GENERATED BY A SCRIPT
  app.post('/forest/actions/create-rent-order', LEA, (req, res) => {
    const {ids} = req.body.data.attributes;

    Promise.resolve()
      .then(() => {
        if ( ids.length > 1 ) {
          throw new Error('Can\'t create multiple rent orders');
        }

        return Renting.scope('room+apartment', 'checkoutDate').findById(ids[0]);
      })
      .then((renting) => {
        return renting.createRentOrder();
      })
      .then(Utils.createSuccessHandler(res, 'Renting Order'))
      .catch(Utils.logAndSend(res));

    return null;
  });

  app.post('/forest/actions/create-pack-order', LEA, (req, res) => {
    const {values, ids} = req.body.data.attributes;

    if ( values.discount != null ) {
      values.discount *= 100;
    }

    Promise.resolve()
      .then(() => {
        if ( !values.comfortLevel ) {
          throw new Error('Please select a comfort level');
        }
        if ( ids.length > 1 ) {
          throw new Error('Can\'t create multiple housing-pack orders');
        }

        return Renting.scope('room+apartment').findById(ids[0]);
      })
      .then((renting) => {
        return renting.findOrCreatePackOrder(values);
      })
      .then(Utils.findOrCreateSuccessHandler(res, 'Housing pack order'))
      .catch(Utils.logAndSend(res));

    return null;
  });

  app.post('/forest/actions/create-deposit-order', LEA, (req, res) => {
    const {ids} = req.body.data.attributes;

    Promise.resolve()
      .then(() => {
        if ( ids.length > 1 ) {
          throw new Error('Can\'t create multiple deposit order');
        }

        return Renting.scope('room+apartment').findById(ids[0]);
      })
      .then((renting) => {
        return renting.findOrCreateDepositOrder();
      })
      .then(Utils.createSuccessHandler(res, 'Deposit order'))
      .catch(Utils.logAndSend(res));
  });

  // add-checkin-date, add-checkout-date, create-checkin-order and
  // create-checkout-order routes
  ['checkin', 'checkout'].forEach((type) => {
    app.post(`/forest/actions/add-${type}-date`, LEA, (req, res) => {
      const {values, ids} = req.body.data.attributes;

      Promise.resolve()
      .then(() => {
        if ( !values.dateAndTime ) {
          throw new Error('Please select a planned date');
        }
        if ( ids.length > 1 ) {
          throw new Error(`Can't create multiple ${type} events`);
        }

        return Renting.scope(
          'room+apartment', // required to create the event
          'client' // required to create the event
        ).findById(ids[0]);
      })
      .then((renting) => {
        return renting[`findOrCreate${_.capitalize(type)}Event`](values.dateAndTime);
      })
      .then(Utils.findOrCreateSuccessHandler(res, `${type} event`))
      .catch(Utils.logAndSend(res));

      return null;
    });

    app.post(`/forest/actions/create-${type}-order`, LEA, (req, res) => {
      const {ids} = req.body.data.attributes;

      Promise.resolve()
        .then(() => {
          if ( ids.length > 1 ) {
            throw new Error(`Can't create multiple ${type} orders`);
          }

          return Renting.scope(
            'client', // required to create the refund event,
            `${type}Date`, // required below
            'comfortLevel' // required below
          ).findById(ids[0]);
        })
        .then((renting) => {
          if ( !renting.get(`${type}Date`) || !renting.get('comfortLevel') ) {
            throw new Error(Utils.stripIndent(`\
              ${_.capitalize(type)} event and housing pack are required to\
              create ${_.capitalize(type)} order`
            ));
          }

          return renting[`findOrCreate${_.capitalize(type)}Order`]();
        })
        .then(Utils.findOrCreateSuccessHandler(res, `${_.capitalize(type)} order`))
        .catch(Utils.logAndSend(res));
      });
  });

  app.post('/forest/actions/room-switch-order', LEA, (req, res) => {
    const {ids, values} = req.body.data.attributes;

    if ( values.discount != null ) {
      values.discount *= 100;
    }

    Promise.resolve()
    .then(() => {
      if ( ids.length > 1 ) {
        throw new Error('Can\'t create multiple room switch orders');
      }

      return Renting.scope(
        'comfortLevel' // required below
      ).findById(ids[0]);
    })
    .then((renting) => {
      if ( renting.get('comfortLevel') == null ) {
        throw new Error('Housing pack is required to create room switch order');
      }

      return renting.createRoomSwitchOrder(values);
    })
    .then(Utils.createSuccessHandler(res, 'Room switch order'))
    .catch(Utils.logAndSend(res));

    return null;
  });

  Utils.addRestoreAndDestroyRoutes(app, Renting);
};
